name: angular_chat
description: A web app that uses AngularDart Components

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.0
  angular_router: ^2.0.0-alpha
  build_config: ^0.3.0
  firebase: ^5.0.0
  meta:
  model: 
    path: ../model  
  rxdart:
  service_worker:

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^0.10.2
  build_test: ^0.10.2
  build_web_compilers: ^0.4.3
  sass_builder: ^2.0.0
  test: ^1.0.0
